### ISSUE TITLE
Error handling is still broken with v6.0.3

### ISSUE THREAD

**Issue by rhegner** [minio/minio-dotnet#1121]
## Expected Behavior
When calling functions like `StatObjectAsync` or `GetObjectAsync`, the SDK should throw exceptions if connection to Minio could not be established.

## Current Behavior
No exceptions are thrown in SDK v6.0.2 and v6.0.3.

This is especially bad in this example where we rely on proper exception handling to detect if an object exists:

```
        private static async Task<bool> Exists(IMinioClient minioClient, string bucket, string objectName)
        {
            try
            {
                var request = new StatObjectArgs()
                    .WithBucket(bucket)
                    .WithObject(objectName);
                await minioClient.StatObjectAsync(request);
                return true;
            }
            catch (ObjectNotFoundException)
            {
                return false;
            }
        }
```

The code returns true even though the Minio server could not even be reached.

## Steps to Reproduce (for bugs)

This is my testbed:

```
using Microsoft.Extensions.Configuration;
using Minio;
using Minio.DataModel.Args;
using Minio.Exceptions;

namespace MinioSdkTest
{
    internal class TestException : Exception;

    internal class Program
    {
        private const string ValidMinioEndpoint = "http://localhost:9000";
        private const string InvalidMinioEndpoint = "http://localhost:9005";
        private const string Bucket = "miniotest";
        private const string ExistingObject = "Rechnung (34).pdf";
        private const string NonexistingObject = "Rechnung (xx).pdf";

        static async Task Main(string[] args)
        {
            // Minio Version                                6.0.0   6.0.1   6.0.2   6.0.3
            // --------------------------------------------------------------------------
            await TestExistsWithExistingObject();       //  ok      ok      ok      ok
            await TestExistsWithNonexistingObject();    //  ok      NOK     ok      ok
            await TestExistsFromInvalidEndpoint();      //  ok      ok      NOK     NOK
            await TestDownloadWithExistingObject();     //  ok      ok      ok      ok
            await TestDownloadWithNonexistingObject();  //  ok      ok      ok      ok
            await TestDownloadFromInvalidEndpoint();    //  ok      ok      NOK     NOK
        }

        private static async Task TestExistsWithExistingObject()
        {
            var minioClient = GetMinioClient(ValidMinioEndpoint);
            var exists = await Exists(minioClient, Bucket, ExistingObject);
            if (!exists)
                throw new TestException();
        }

        private static async Task TestExistsWithNonexistingObject()
        {
            var minioClient = GetMinioClient(ValidMinioEndpoint);
            var exists = await Exists(minioClient, Bucket, NonexistingObject);
            if (exists)
                throw new TestException();
        }

        private static async Task TestExistsFromInvalidEndpoint()
        {
            try
            {
                var minioClient = GetMinioClient(InvalidMinioEndpoint);
                var exists = await Exists(minioClient, Bucket, NonexistingObject);
                throw new TestException();  // we should never get here
            }
            catch (TestException)
            {
                throw;
            }
            catch (ConnectionException)
            {
                // this is the expected outcome (throw exception if trying to access invalid endpoint)
            }
        }

        private static async Task TestDownloadWithExistingObject()
        {
            var minioClient = GetMinioClient(ValidMinioEndpoint);
            var data = await Download(minioClient, Bucket, ExistingObject);
            if (data.Length == 0)
                throw new TestException();
        }

        private static async Task TestDownloadWithNonexistingObject()
        {
            try
            {
                var minioClient = GetMinioClient(ValidMinioEndpoint);
                var data = await Download(minioClient, Bucket, NonexistingObject);
                throw new TestException();  // we should never get here
            }
            catch (TestException)
            {
                throw;
            }
            catch (ObjectNotFoundException)
            {
                // this is the expected outcome (throw exception if trying to access nonexisting object)
            }
        }

        private static async Task TestDownloadFromInvalidEndpoint()
        {
            try
            {
                var minioClient = GetMinioClient(InvalidMinioEndpoint);
                var data = await Download(minioClient, Bucket, NonexistingObject);
                throw new TestException();  // we should never get here
            }
            catch (TestException)
            {
                throw;
            }
            catch (ConnectionException)
            {
                // this is the expected outcome (throw exception if trying to access invalid endpoint)
            }
        }

        private static async Task<bool> Exists(IMinioClient minioClient, string bucket, string objectName)
        {
            try
            {
                var request = new StatObjectArgs()
                    .WithBucket(bucket)
                    .WithObject(objectName);
                await minioClient.StatObjectAsync(request);
                return true;
            }
            catch (ObjectNotFoundException)
            {
                return false;
            }
        }

        private static async Task<Stream> Download(IMinioClient minioClient, string bucket, string objectName)
        {
            var stream = new MemoryStream();
            try
            {
                var request = new GetObjectArgs()
                    .WithBucket(bucket)
                    .WithObject(objectName)
                    .WithCallbackStream((s, ct) => s.CopyToAsync(stream, ct));
                await minioClient.GetObjectAsync(request);
                stream.Position = 0;
                return stream;
            }
            catch
            {
                stream.Dispose();
                throw;
            }
        }

        private static IMinioClient GetMinioClient(string endpoint)
        {
            var configuration = new ConfigurationBuilder().AddUserSecrets<Program>().Build();
            var accessKey = configuration["minio_access_key"];
            var secretKey = configuration["minio_secret_key"];

            var endpointUri = new Uri(endpoint);
            var minioClient = new MinioClient()
                .WithEndpoint(endpointUri.Authority)   // Authority is host:port
                .WithCredentials(accessKey, secretKey);
            if (endpointUri.Scheme == "https")
                minioClient.WithSSL();
            minioClient.Build();
            return minioClient;
        }
    }
}

```

## Regression

Error handling is broken (in different ways) since v6.0.1.

## Your Environment
Minio 6.0.3

**Comment by harshavardhana** [comment]
Moving it to relevant project

**Comment by ebozduman** [comment]
Reproduced it and working on it.

**Comment by codewing** [comment]
`PutObjectAsync` and `BucketExistsAsync` also seem to ignore errors in 6.0.3 (6.0.1 is fine)

**Comment by ebozduman** [comment]
@codewing 
Thank you for the info.

**Comment by ebozduman** [comment]
I think canlar#1141 has fixed several issues including this one.
I appreciate if you could let me know about your test results and findings.                                                          m,

**Comment by rhegner** [comment]
@ebozduman I did not run my tests yet, but just from looking at the code I still have some concerns regarding error handling, see https://github.com/minio/minio-dotnet/pull/1141#issuecomment-2250123299

**Comment by ebozduman** [comment]
@rhegner 

I agree the error handling is complex and problematic and its maintenance and testing is cumbersome.
Until it is  redesigned though, we have to support it IMHO, or until mngmt makes a decision about it.

I appreciate it if you could test the fix in your environment and let us know an of course open up a new issue if required.

**Comment by tinohager** [comment]
What about the problem? Is there anything else going on here?

**Comment by ebozduman** [comment]
@tinohager 

There is some work that has been done and completed to fix the issue, but testing the fix and tuning it up for all possible scenarios requires considerable amount of time.
Unfortunately, sometimes a higher priority task might slow down the progress of this issue and the reviewers are expected to be extremely thorough when the fix is ready.

**Comment by tinohager** [comment]
Maybe you should at least mark the package in Nuget/Github that there are problems with the current version.
`Pin Issue`

**Comment by ItsJustRuby** [comment]
I would welcome any development on this issue at all.

Just to emphasize, anyone currently starting a new project and using the most recent version of the NuGet package will get 0 error reporting and handling if they make any mistake setting up any Minio integration.

For any unfortunate future reader: I could personally fix my issue by adding `.WithSSL(false)` to give me:
```csharp
        services.AddMinio(options =>
        {
            options
                .WithEndpoint(config["STORAGE_ENDPOINT"])
                .WithCredentials(config["STORAGE_ACCESS_KEY"], config["STORAGE_SECRET_KEY"])
                .WithSSL(false)
                .Build();
        });
```

**Comment by ebozduman** [comment]
@wardboumans 
Thank you for  confirming it.
We are aware of it and unfortunately it took a long time to address it.
It is reevaluated and will be addressed again and available in a month frame.

**Comment by rhegner** [comment]
Unfortunately v6.0.4 does not resolve this:

```
// Minio Version                                6.0.0   6.0.1   6.0.2   6.0.3   6.0.4
// ----------------------------------------------------------------------------------
await TestExistsWithExistingObject();       //  ok      ok      ok      ok      ok
await TestExistsWithNonexistingObject();    //  ok      NOK     ok      ok      ok
await TestExistsFromInvalidEndpoint();      //  ok      ok      NOK     NOK     NOK
await TestDownloadWithExistingObject();     //  ok      ok      ok      ok      ok
await TestDownloadWithNonexistingObject();  //  ok      ok      ok      ok      ok
await TestDownloadFromInvalidEndpoint();    //  ok      ok      NOK     NOK     NOK
await TestWithInvalidCredentials();         //  ok      ok      NOK     NOK     NOK
```

We are still stuck with v6.0.0, as the error handling is completely broken with all newer versions!

**Comment by ebozduman** [comment]
@rhegner 
That is unfortunately correct. 
Sorry, I don't have a definitive date at this point, but it'll be addressed soon.

**Comment by bri-bsw** [comment]
Hi,

we are also having this issue with 6.0.4. Will there be a solution soon?
Best regards,

Patrick

**Comment by ebozduman** [comment]
@bri-bsw 
Working on it.
My guesstimate is a couple of weeks.

**Comment by Ferro6** [comment]
Hi,
I have the same problem (with version 6.0.4)
Any news about the resolution?

**Comment by Todilo** [comment]
How can any version with this bug even be available in the nuget store? Lots of api method just outright lies (BucketExistsAsync for instance returns true despite no connection being made) . Anyone using examples from official documentation will be mislead. At least put a disclaimer on the official documentation?

**Comment by n-goncalves** [comment]
This [comment inside a PR](https://github.com/minio/minio-dotnet/pull/1141#issuecomment-2632093294) talks about "marking the versions as unstable" back in February but nothing was done to this day.

Totally agree with what @Todilo said, it is really disappointing that the only way to know of this issue is to have the library not working as it's supposed to and end up here trying to find the root cause.

It's not a good outlook having error handling broken for more than 1 year and more than 6 months after being reported.

**Comment by ebozduman** [comment]
I apologize for the delay.
I've asked the builds to be marked as unstable a couple of times, but it fell through the cracks and I failed to follow up.
There will be a PR to address this issue in 3-4 days and if the internal reviewers agree, we'll merge it to create  a new package.

**Comment by tinohager** [comment]
@ebozduman I wanted to trigger again as 4 days have already passed  😆 

In the meantime, I recommend marking the package as buggy on nuget and pinning the issue on github.

**nuget.org**
![Image](https://github.com/user-attachments/assets/fc2841ef-c0ed-495d-be25-2daf2d817ef5)

**Comment by ebozduman** [comment]
@tinohager 

I requested the nuget package to be marked as buggy/deprecated.

A fix for this issue is pushed into the PR, #1141. 
Although I've tested all features before the PR is created, some build tests still failed.
These failures will be addressed this week.

**Comment by tinohager** [comment]
@ebozduman Not much has happened yet. You know that you can mark the package as faulty yourself on NuGet.

![Image](https://github.com/user-attachments/assets/9d751851-de80-45a1-a41e-ec774093d8c3)

**Comment by Willimaendu** [comment]
Any news? It's still buggy in 6.0.4 since almost a year!

**Comment by ebozduman** [comment]
PR#1141 is ready to be reviewed but nobody had time to review the fix.
I expect PR#1141 to resolve the major missing exception issue in 6.0.4 and other broken older releases since 6.0

**Comment by loekensgard** [comment]
Any idea when this will be merged?

**Comment by ebozduman** [comment]
Comments are incorporated.
Found some issues in `dotnet regitlint` output for an object not having a method, however this does not cause any problem during `dotnet build` and the tests run successfully. The code/test, which has the problematic code, was commented out in the previous releases. 
To push forward, I might comment again after spending another day on it. If I cannot understand and resolve the issue, I'll comment out this test again to move on with the new release. I expect to start the release process next week.

**Comment by loekensgard** [comment]
@ebozduman, this is fixed in 6.0.5?

**Comment by ebozduman** [comment]
@loekensgard 
Yes, exceptions are captured bucket exist check fixes are all in 6.0.5.
The only left over part, which is already addressed in a separate PR (#1306) and waiting to be code reviewed, is the thrown exceptions are regressed when an invalid server endpoint/access key/secret key are provided.
As soon as the code review is completed, there will be another release 6.0.6.

**Comment by AmBplus** [comment]
A series of errors, such as null object and bucket-related issues, in version 6.03 appear to be related to time-related problems. I have documented these issues in the referenced issue report.

**Comment by ebozduman** [comment]
@AmBplus ,
Yes. This is a regression. 
But, I'd like to recommend using 6.0.5 instead of 6.0.3 as the behavior could have changed in the latest release.
We are working on the regressions and a couple of known and a couple of newly found regressions will be addressed in the next release.

**Comment by ebozduman** [comment]
@tinohager 
I was told that we don't do alpha or beta releases.
I guess the other option is `github.com`.

**Comment by rhegner** [comment]
Hello, I just tested v7.0.0. It looks a bit better than 6.0.5, but still behaves differently than 6.0.0:

```
// Minio Version                                6.0.0   6.0.1   6.0.2   6.0.3   6.0.4   6.0.5   7.0.0
// --------------------------------------------------------------------------------------------------
await TestExistsWithExistingObject();       //  ok      ok      ok      ok      ok      ok      ok
await TestExistsWithNonexistingObject();    //  ok      NOK     ok      ok      ok      ok      ok
await TestExistsFromInvalidEndpoint();      //  ok      ok      NOK     NOK     NOK     NOK     NOK
await TestDownloadWithExistingObject();     //  ok      ok      ok      ok      ok      ok      ok
await TestDownloadWithNonexistingObject();  //  ok      ok      ok      ok      ok      ok      ok
await TestDownloadFromInvalidEndpoint();    //  ok      ok      NOK     NOK     NOK     NOK     NOK
await TestWithInvalidCredentials();         //  ok      ok      NOK     NOK     NOK     NOK     ok
```

When providing an invalid endpoint, v7.0.0 throws a `System.Net.Http.HttpRequestException` while v6.0.0 throws a `Minio.Exceptions.ConnectionException`.

Is that change intended? If so, in what case do we get a `Minio.Exceptions.ConnectionException` (which still exists as type in v7.0.0)?
